### ISSUE TITLE
В чём смысл сортировать "два раза"?

### ISSUE THREAD

**Issue by coursar** [rufattabaev/Citilink#5]
https://github.com/rufattabaev/Citilink/blob/6701d12fcdf8f5827fd4166506d085315de6317e/src/main/java/ru/itpark/service/CitilinkService.java#L71-L72

Это бессмысленно, т.к. вторая сортировка буквально игнорирует результаты первой.

**Comment by rufattabaev** [comment]
public List<Product> searchByName(String name) {
        List<Product> result = new LinkedList<>();
        for (Product product : repository.getAll()) {
            if (product.getName().contains(name)) {
                result.add(product);
            }
        }
        result.sort((o1, o2) -> o1.getName().compareToIgnoreCase(o2.getName()));
        return result;
    }

Исправил.
